"""
MetaLex Demo Data Service
Provides sample inspection data for demonstration when OCR is unavailable or
for the judge demo flow.

All demo data is clearly labeled as DEMO DATA.
"""
import uuid
import datetime

DEMO_PRODUCTS = [
    {
        "id": "demo-001",
        "name": "Tata Premium Tea",
        "description": "Fully compliant product — all declarations present",
        "is_compliant": True,
        "fields": {
            "product_name": {
                "value": "Tata Premium Tea",
                "normalized_value": "Tata Premium Tea",
                "confidence": 0.96,
                "bounding_box": [45, 20, 320, 80],
                "source_text": "TATA PREMIUM TEA",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Tata Premium Tea", "confidence": 0.96, "score": 0.98}],
            },
            "net_quantity": {
                "value": "500 g",
                "normalized_value": "500g",
                "confidence": 0.94,
                "bounding_box": [50, 310, 180, 345],
                "source_text": "Net Wt: 500 g",
                "extraction_method": "demo_data",
                "candidates": [{"value": "500 g", "confidence": 0.94, "score": 0.95}],
            },
            "mrp": {
                "value": "₹199",
                "normalized_value": "₹199",
                "confidence": 0.93,
                "bounding_box": [50, 350, 200, 385],
                "source_text": "MRP: ₹199 (Inclusive of all taxes)",
                "extraction_method": "demo_data",
                "candidates": [{"value": "₹199", "confidence": 0.93, "score": 0.95}],
            },
            "manufacturer": {
                "value": "Tata Consumer Products Ltd",
                "normalized_value": "Tata Consumer Products Ltd",
                "confidence": 0.91,
                "bounding_box": [30, 400, 380, 440],
                "source_text": "Manufactured by: Tata Consumer Products Ltd",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Tata Consumer Products Ltd", "confidence": 0.91, "score": 0.93}],
            },
            "date": {
                "value": "Jul 2026",
                "normalized_value": "07/2026",
                "confidence": 0.89,
                "bounding_box": [50, 450, 200, 480],
                "source_text": "Mfg Date: Jul 2026",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Jul 2026", "confidence": 0.89, "score": 0.90}],
            },
            "consumer_care": {
                "value": "1800-209-8787",
                "normalized_value": "1800-209-8787",
                "confidence": 0.88,
                "bounding_box": [30, 490, 350, 525],
                "source_text": "Consumer Care: 1800-209-8787 | care@tataconsumer.com",
                "extraction_method": "demo_data",
                "candidates": [{"value": "1800-209-8787", "confidence": 0.88, "score": 0.90}],
            },
            "country_of_origin": {
                "value": "India",
                "normalized_value": "India",
                "confidence": 0.92,
                "bounding_box": [50, 530, 200, 560],
                "source_text": "Country of Origin: India",
                "extraction_method": "demo_data",
                "candidates": [{"value": "India", "confidence": 0.92, "score": 0.93}],
            },
            "address": {
                "value": "Kolkata, West Bengal, 700001",
                "normalized_value": "Kolkata, West Bengal, 700001",
                "confidence": 0.85,
                "bounding_box": [30, 440, 380, 470],
                "source_text": "Regd. Off: Kolkata, West Bengal, 700001",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Kolkata, West Bengal, 700001", "confidence": 0.85, "score": 0.87}],
            },
            "common_name": {
                "value": "Tea",
                "normalized_value": "Tea",
                "confidence": 0.90,
                "bounding_box": [200, 85, 280, 110],
                "source_text": "Tea",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Tea", "confidence": 0.90, "score": 0.90}],
            },
        },
    },
    {
        "id": "demo-002",
        "name": "QuickBite Instant Noodles",
        "description": "Missing MRP — non-compliant product",
        "is_compliant": False,
        "fields": {
            "product_name": {
                "value": "QuickBite Instant Noodles",
                "normalized_value": "QuickBite Instant Noodles",
                "confidence": 0.95,
                "bounding_box": [30, 15, 350, 75],
                "source_text": "QuickBite INSTANT NOODLES",
                "extraction_method": "demo_data",
                "candidates": [{"value": "QuickBite Instant Noodles", "confidence": 0.95, "score": 0.97}],
            },
            "net_quantity": {
                "value": "70 g",
                "normalized_value": "70g",
                "confidence": 0.92,
                "bounding_box": [40, 300, 160, 330],
                "source_text": "Net Weight: 70 g",
                "extraction_method": "demo_data",
                "candidates": [{"value": "70 g", "confidence": 0.92, "score": 0.93}],
            },
            "mrp": {
                "value": None,
                "normalized_value": None,
                "confidence": 0.0,
                "bounding_box": None,
                "source_text": "",
                "extraction_method": "not_detected",
                "candidates": [],
            },
            "manufacturer": {
                "value": "QuickBite Foods Pvt Ltd",
                "normalized_value": "QuickBite Foods Pvt Ltd",
                "confidence": 0.88,
                "bounding_box": [25, 370, 370, 410],
                "source_text": "Manufactured by: QuickBite Foods Pvt Ltd",
                "extraction_method": "demo_data",
                "candidates": [{"value": "QuickBite Foods Pvt Ltd", "confidence": 0.88, "score": 0.90}],
            },
            "date": {
                "value": "06/2026",
                "normalized_value": "06/2026",
                "confidence": 0.91,
                "bounding_box": [40, 420, 180, 450],
                "source_text": "Pkg Date: 06/2026",
                "extraction_method": "demo_data",
                "candidates": [{"value": "06/2026", "confidence": 0.91, "score": 0.92}],
            },
            "consumer_care": {
                "value": "support@quickbite.in",
                "normalized_value": "support@quickbite.in",
                "confidence": 0.86,
                "bounding_box": [25, 460, 340, 490],
                "source_text": "For queries: support@quickbite.in",
                "extraction_method": "demo_data",
                "candidates": [{"value": "support@quickbite.in", "confidence": 0.86, "score": 0.88}],
            },
            "country_of_origin": {
                "value": "India",
                "normalized_value": "India",
                "confidence": 0.90,
                "bounding_box": [40, 500, 180, 525],
                "source_text": "Made in India",
                "extraction_method": "demo_data",
                "candidates": [{"value": "India", "confidence": 0.90, "score": 0.91}],
            },
            "address": {
                "value": "Noida, Uttar Pradesh, 201301",
                "normalized_value": "Noida, Uttar Pradesh, 201301",
                "confidence": 0.84,
                "bounding_box": [25, 410, 370, 440],
                "source_text": "Noida, Uttar Pradesh, 201301",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Noida, Uttar Pradesh, 201301", "confidence": 0.84, "score": 0.86}],
            },
            "common_name": {
                "value": "Instant Noodles",
                "normalized_value": "Instant Noodles",
                "confidence": 0.90,
                "bounding_box": [100, 70, 280, 95],
                "source_text": "Instant Noodles",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Instant Noodles", "confidence": 0.90, "score": 0.91}],
            },
        },
    },
    {
        "id": "demo-003",
        "name": "FreshWash Detergent",
        "description": "Missing consumer care details — non-compliant",
        "is_compliant": False,
        "fields": {
            "product_name": {
                "value": "FreshWash Detergent Powder",
                "normalized_value": "FreshWash Detergent Powder",
                "confidence": 0.94,
                "bounding_box": [35, 20, 340, 70],
                "source_text": "FRESHWASH DETERGENT POWDER",
                "extraction_method": "demo_data",
                "candidates": [{"value": "FreshWash Detergent Powder", "confidence": 0.94, "score": 0.96}],
            },
            "net_quantity": {
                "value": "1 kg",
                "normalized_value": "1kg",
                "confidence": 0.93,
                "bounding_box": [45, 290, 150, 320],
                "source_text": "Net Weight: 1 kg",
                "extraction_method": "demo_data",
                "candidates": [{"value": "1 kg", "confidence": 0.93, "score": 0.94}],
            },
            "mrp": {
                "value": "₹89",
                "normalized_value": "₹89",
                "confidence": 0.91,
                "bounding_box": [45, 330, 180, 360],
                "source_text": "MRP ₹89 (Incl. all taxes)",
                "extraction_method": "demo_data",
                "candidates": [{"value": "₹89", "confidence": 0.91, "score": 0.93}],
            },
            "manufacturer": {
                "value": "CleanCorp Industries",
                "normalized_value": "CleanCorp Industries",
                "confidence": 0.87,
                "bounding_box": [30, 380, 350, 415],
                "source_text": "Mfd by: CleanCorp Industries",
                "extraction_method": "demo_data",
                "candidates": [{"value": "CleanCorp Industries", "confidence": 0.87, "score": 0.89}],
            },
            "date": {
                "value": "Aug 2026",
                "normalized_value": "08/2026",
                "confidence": 0.90,
                "bounding_box": [45, 430, 190, 455],
                "source_text": "Mfg Date: Aug 2026",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Aug 2026", "confidence": 0.90, "score": 0.91}],
            },
            "consumer_care": {
                "value": None,
                "normalized_value": None,
                "confidence": 0.0,
                "bounding_box": None,
                "source_text": "",
                "extraction_method": "not_detected",
                "candidates": [],
            },
            "country_of_origin": {
                "value": "India",
                "normalized_value": "India",
                "confidence": 0.89,
                "bounding_box": [45, 470, 170, 495],
                "source_text": "Country of Origin: India",
                "extraction_method": "demo_data",
                "candidates": [{"value": "India", "confidence": 0.89, "score": 0.90}],
            },
            "address": {
                "value": "Mumbai, Maharashtra, 400001",
                "normalized_value": "Mumbai, Maharashtra, 400001",
                "confidence": 0.83,
                "bounding_box": [30, 415, 350, 445],
                "source_text": "Regd Office: Mumbai, Maharashtra, 400001",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Mumbai, Maharashtra, 400001", "confidence": 0.83, "score": 0.85}],
            },
            "common_name": {
                "value": "Detergent Powder",
                "normalized_value": "Detergent Powder",
                "confidence": 0.88,
                "bounding_box": [120, 65, 290, 90],
                "source_text": "Detergent Powder",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Detergent Powder", "confidence": 0.88, "score": 0.89}],
            },
        },
    },
    {
        "id": "demo-004",
        "name": "GlowFit Protein Bar",
        "description": "Poor OCR / ambiguous text — needs review",
        "is_compliant": None,  # NEEDS_REVIEW
        "fields": {
            "product_name": {
                "value": "GlowFit Protein Bar",
                "normalized_value": "GlowFit Protein Bar",
                "confidence": 0.72,
                "bounding_box": [30, 15, 330, 65],
                "source_text": "Gl0wFit Prot3in Bar",
                "extraction_method": "demo_data",
                "candidates": [
                    {"value": "GlowFit Protein Bar", "confidence": 0.72, "score": 0.75},
                    {"value": "Gl0wFit Prot3in Bar", "confidence": 0.45, "score": 0.50},
                ],
            },
            "net_quantity": {
                "value": "60g",
                "normalized_value": "60g",
                "confidence": 0.55,
                "bounding_box": [40, 280, 140, 310],
                "source_text": "Net Wt: 6Og",
                "extraction_method": "demo_data",
                "candidates": [
                    {"value": "60g", "confidence": 0.55, "score": 0.60},
                    {"value": "6Og", "confidence": 0.40, "score": 0.45},
                ],
            },
            "mrp": {
                "value": "₹I99",
                "normalized_value": "₹199",
                "confidence": 0.42,
                "bounding_box": [40, 320, 170, 350],
                "source_text": "MRP: ₹I99",
                "extraction_method": "demo_data",
                "candidates": [
                    {"value": "₹I99", "confidence": 0.42, "score": 0.50},
                    {"value": "₹199", "confidence": 0.38, "score": 0.45},
                ],
            },
            "manufacturer": {
                "value": "GlowFit Nutrition Pvt Ltd",
                "normalized_value": "GlowFit Nutrition Pvt Ltd",
                "confidence": 0.58,
                "bounding_box": [25, 370, 360, 400],
                "source_text": "Mfd by: Gl0wFit Nutritio n Pvt Ltd",
                "extraction_method": "demo_data",
                "candidates": [{"value": "GlowFit Nutrition Pvt Ltd", "confidence": 0.58, "score": 0.62}],
            },
            "date": {
                "value": "O5/2O26",
                "normalized_value": "05/2026",
                "confidence": 0.40,
                "bounding_box": [40, 410, 180, 440],
                "source_text": "Mfg: O5/2O26",
                "extraction_method": "demo_data",
                "candidates": [
                    {"value": "O5/2O26", "confidence": 0.40, "score": 0.45},
                    {"value": "05/2026", "confidence": 0.35, "score": 0.40},
                ],
            },
            "consumer_care": {
                "value": "1800-1O0-9876",
                "normalized_value": "1800-100-9876",
                "confidence": 0.48,
                "bounding_box": [25, 450, 340, 480],
                "source_text": "Consumer Helpline: 1800-1O0-9876",
                "extraction_method": "demo_data",
                "candidates": [{"value": "1800-1O0-9876", "confidence": 0.48, "score": 0.52}],
            },
            "country_of_origin": {
                "value": "India",
                "normalized_value": "India",
                "confidence": 0.65,
                "bounding_box": [40, 490, 160, 515],
                "source_text": "Made in lndia",
                "extraction_method": "demo_data",
                "candidates": [{"value": "India", "confidence": 0.65, "score": 0.68}],
            },
            "address": {
                "value": "Bengaluru, Karnataka",
                "normalized_value": "Bengaluru, Karnataka",
                "confidence": 0.52,
                "bounding_box": [25, 400, 350, 430],
                "source_text": "8engaluru, Karnat aka",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Bengaluru, Karnataka", "confidence": 0.52, "score": 0.55}],
            },
            "common_name": {
                "value": None,
                "normalized_value": None,
                "confidence": 0.0,
                "bounding_box": None,
                "source_text": "",
                "extraction_method": "not_detected",
                "candidates": [],
            },
        },
    },
    {
        "id": "demo-005",
        "name": "AquaPure Mineral Water",
        "description": "Multiple violations — missing manufacturer, date, consumer care",
        "is_compliant": False,
        "fields": {
            "product_name": {
                "value": "AquaPure Mineral Water",
                "normalized_value": "AquaPure Mineral Water",
                "confidence": 0.97,
                "bounding_box": [40, 25, 340, 80],
                "source_text": "AQUAPURE MINERAL WATER",
                "extraction_method": "demo_data",
                "candidates": [{"value": "AquaPure Mineral Water", "confidence": 0.97, "score": 0.98}],
            },
            "net_quantity": {
                "value": "1 L",
                "normalized_value": "1L",
                "confidence": 0.95,
                "bounding_box": [50, 300, 140, 330],
                "source_text": "1 Litre",
                "extraction_method": "demo_data",
                "candidates": [{"value": "1 L", "confidence": 0.95, "score": 0.96}],
            },
            "mrp": {
                "value": "₹20",
                "normalized_value": "₹20",
                "confidence": 0.94,
                "bounding_box": [50, 340, 160, 370],
                "source_text": "MRP: ₹20",
                "extraction_method": "demo_data",
                "candidates": [{"value": "₹20", "confidence": 0.94, "score": 0.95}],
            },
            "manufacturer": {
                "value": None,
                "normalized_value": None,
                "confidence": 0.0,
                "bounding_box": None,
                "source_text": "",
                "extraction_method": "not_detected",
                "candidates": [],
            },
            "date": {
                "value": None,
                "normalized_value": None,
                "confidence": 0.0,
                "bounding_box": None,
                "source_text": "",
                "extraction_method": "not_detected",
                "candidates": [],
            },
            "consumer_care": {
                "value": None,
                "normalized_value": None,
                "confidence": 0.0,
                "bounding_box": None,
                "source_text": "",
                "extraction_method": "not_detected",
                "candidates": [],
            },
            "country_of_origin": {
                "value": None,
                "normalized_value": None,
                "confidence": 0.0,
                "bounding_box": None,
                "source_text": "",
                "extraction_method": "not_detected",
                "candidates": [],
            },
            "address": {
                "value": None,
                "normalized_value": None,
                "confidence": 0.0,
                "bounding_box": None,
                "source_text": "",
                "extraction_method": "not_detected",
                "candidates": [],
            },
            "common_name": {
                "value": "Mineral Water",
                "normalized_value": "Mineral Water",
                "confidence": 0.92,
                "bounding_box": [120, 75, 270, 100],
                "source_text": "Mineral Water",
                "extraction_method": "demo_data",
                "candidates": [{"value": "Mineral Water", "confidence": 0.92, "score": 0.93}],
            },
        },
    },
]


def get_demo_products():
    return DEMO_PRODUCTS


def get_demo_product(product_id: str):
    for p in DEMO_PRODUCTS:
        if p["id"] == product_id:
            return p
    return None
